// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUttwVKakq6hBau1MyR30NZtSbx3Cxo9A',
    appId: '1:923664715542:web:66c30213b988e2c2fb4a37',
    messagingSenderId: '923664715542',
    projectId: 'obexvault',
    authDomain: 'obexvault.firebaseapp.com',
    storageBucket: 'obexvault.firebasestorage.app',
    measurementId: 'G-GTBZ8HXYYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtCiPSGoU-DdpgfmlqVEr_jjNSTCQsao0',
    appId: '1:923664715542:android:33954502b7782a86fb4a37',
    messagingSenderId: '923664715542',
    projectId: 'obexvault',
    storageBucket: 'obexvault.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiEJBtUqb0f3vF_7h5qMouqg4Y3wDHQ8Q',
    appId: '1:923664715542:ios:3403c7c72d31ef84fb4a37',
    messagingSenderId: '923664715542',
    projectId: 'obexvault',
    storageBucket: 'obexvault.firebasestorage.app',
    iosClientId: '923664715542-frnu7gbaeuu0nq8ag00qb5c5vfcnspif.apps.googleusercontent.com',
    iosBundleId: 'com.atharva.obexvault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiEJBtUqb0f3vF_7h5qMouqg4Y3wDHQ8Q',
    appId: '1:923664715542:ios:3403c7c72d31ef84fb4a37',
    messagingSenderId: '923664715542',
    projectId: 'obexvault',
    storageBucket: 'obexvault.firebasestorage.app',
    iosClientId: '923664715542-frnu7gbaeuu0nq8ag00qb5c5vfcnspif.apps.googleusercontent.com',
    iosBundleId: 'com.atharva.obexvault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUttwVKakq6hBau1MyR30NZtSbx3Cxo9A',
    appId: '1:923664715542:web:4f379ee1dcc6c6d9fb4a37',
    messagingSenderId: '923664715542',
    projectId: 'obexvault',
    authDomain: 'obexvault.firebaseapp.com',
    storageBucket: 'obexvault.firebasestorage.app',
    measurementId: 'G-TZ1JZ60R1Q',
  );
}
